[theme]
primaryColor="#E00000"               # Rojo Spider-Man
backgroundColor="#0D2C54"            # Azul marino (FONDO principal)
secondaryBackgroundColor="#7A0E1A"   # Rojo vino (LATERAL / sidebar)
textColor="#FFFFFF"                  # Blanco
font="sans serif"               
